# Generated by Django 3.2.3 on 2021-06-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210605_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='uncategorized', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.CharField(default='', max_length=200),
        ),
    ]
