# Generated by Django 3.2.3 on 2021-06-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20210609_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commenter_str',
            field=models.CharField(default='Anonymous', max_length=200),
        ),
    ]
