# Generated by Django 3.2.3 on 2021-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_comments_commenter_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='viewable',
            field=models.BooleanField(default=False),
        ),
    ]
