# Generated by Django 3.2.3 on 2021-06-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comments_viewable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenter_str',
            field=models.CharField(default='Anonymous', max_length=2000),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
