# Generated by Django 3.2.3 on 2021-06-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='related_posts', to='blog.Category'),
        ),
    ]
