# Generated by Django 3.2.3 on 2021-06-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visited', to='blog.posts'),
        ),
    ]
